services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    depends_on:
      - api
      - frontend

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - event_postgres_data:/var/lib/postgresql/data
      - ./event-api/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  mailpit:
    image: axllent/mailpit:latest
    container_name: event-platform-mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    restart: unless-stopped

  api:
    build:
      context: ./event-manager-microservice-api
    container_name: event-platform-api
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: ${POSTGRES_INTERNAL_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: ./event-manager-frontend/Dockerfile
      args:
        VITE_API_URL: ${API_URL}
        VITE_API_PATH: ${API_PATH}
        VITE_GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    container_name: event-platform-frontend
    restart: unless-stopped
    expose:
      - "5173"

volumes:
  event_postgres_data:
